### ISSUE TITLE
Use codeblock instead inline code

### ISSUE THREAD

**Issue by LilTeo14** [BinaryQuantumSoul/discord-latex#6] opened 2024-08-06 22:00 UTC
Hello i am using the plugin to display discord chat gpt bot answers, but chatgpt bot usually answer with codeblocks(3 backquote) instead inlinecode(1 backquote), i would like to make the plugin work with codeblocks and inlinecode anyway the bot is amazing great job.

**Comment by BinaryQuantumSoul** [comment] 2024-08-07 22:00
Hello really interesting to see other use cases of my plugin!

Unfortunately, I was not able yet to find a trick for it to work since last time I checked there was weird discord html formatting for the codeblocks which prevented plugin from working. I didn't take time to investigate further yet.

Thanks for the kinds words :)

**Comment by BinaryQuantumSoul** [comment] 2024-08-07 22:02
Duplicate of #2

**Closed as completed** 2024-08-15 07:08 UTC
